<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20180903175705 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
        $this->addSql('CREATE TABLE country (iso_alpha3 VARCHAR(3) NOT NULL, country_code VARCHAR(2) NOT NULL, currency_code VARCHAR(3) NOT NULL, PRIMARY KEY(iso_alpha3)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('INSERT INTO country (country_code, currency_code, iso_alpha3) VALUES
(\'AD\', \'EUR\', \'AND\'),
(\'AE\', \'AED\', \'ARE\'),
(\'AF\', \'AFN\', \'AFG\'),
(\'AG\', \'XCD\', \'ATG\'),
(\'AI\', \'XCD\', \'AIA\'),
(\'AL\', \'ALL\', \'ALB\'),
(\'AM\', \'AMD\', \'ARM\'),
(\'AO\', \'AOA\', \'AGO\'),
(\'AQ\', \'\', \'ATA\'),
(\'AR\', \'ARS\', \'ARG\'),
(\'AS\', \'USD\', \'ASM\'),
(\'AT\', \'EUR\', \'AUT\'),
(\'AU\', \'AUD\', \'AUS\'),
(\'AW\', \'AWG\', \'ABW\'),
(\'AX\', \'EUR\', \'ALA\'),
(\'AZ\', \'AZN\', \'AZE\'),
(\'BA\', \'BAM\', \'BIH\'),
(\'BB\', \'BBD\', \'BRB\'),
(\'BD\', \'BDT\', \'BGD\'),
(\'BE\', \'EUR\', \'BEL\'),
(\'BF\', \'XOF\', \'BFA\'),
(\'BG\', \'BGN\', \'BGR\'),
(\'BH\', \'BHD\', \'BHR\'),
(\'BI\', \'BIF\', \'BDI\'),
(\'BJ\', \'XOF\', \'BEN\'),
(\'BL\', \'EUR\', \'BLM\'),
(\'BM\', \'BMD\', \'BMU\'),
(\'BN\', \'BND\', \'BRN\'),
(\'BO\', \'BOB\', \'BOL\'),
(\'BQ\', \'USD\', \'BES\'),
(\'BR\', \'BRL\', \'BRA\'),
(\'BS\', \'BSD\', \'BHS\'),
(\'BT\', \'BTN\', \'BTN\'),
(\'BV\', \'NOK\', \'BVT\'),
(\'BW\', \'BWP\', \'BWA\'),
(\'BY\', \'BYR\', \'BLR\'),
(\'BZ\', \'BZD\', \'BLZ\'),
(\'CA\', \'CAD\', \'CAN\'),
(\'CC\', \'AUD\', \'CCK\'),
(\'CD\', \'CDF\', \'COD\'),
(\'CF\', \'XAF\', \'CAF\'),
(\'CG\', \'XAF\', \'COG\'),
(\'CH\', \'CHF\', \'CHE\'),
(\'CI\', \'XOF\', \'CIV\'),
(\'CK\', \'NZD\', \'COK\'),
(\'CL\', \'CLP\', \'CHL\'),
(\'CM\', \'XAF\', \'CMR\'),
(\'CN\', \'CNY\', \'CHN\'),
(\'CO\', \'COP\', \'COL\'),
(\'CR\', \'CRC\', \'CRI\'),
(\'CU\', \'CUP\', \'CUB\'),
(\'CV\', \'CVE\', \'CPV\'),
(\'CW\', \'ANG\', \'CUW\'),
(\'CX\', \'AUD\', \'CXR\'),
(\'CY\', \'EUR\', \'CYP\'),
(\'CZ\', \'CZK\', \'CZE\'),
(\'DE\', \'EUR\', \'DEU\'),
(\'DJ\', \'DJF\', \'DJI\'),
(\'DK\', \'DKK\', \'DNK\'),
(\'DM\', \'XCD\', \'DMA\'),
(\'DO\', \'DOP\', \'DOM\'),
(\'DZ\', \'DZD\', \'DZA\'),
(\'EC\', \'USD\', \'ECU\'),
(\'EE\', \'EUR\', \'EST\'),
(\'EG\', \'EGP\', \'EGY\'),
(\'EH\', \'MAD\', \'ESH\'),
(\'ER\', \'ERN\', \'ERI\'),
(\'ES\', \'EUR\', \'ESP\'),
(\'ET\', \'ETB\', \'ETH\'),
(\'FI\', \'EUR\', \'FIN\'),
(\'FJ\', \'FJD\', \'FJI\'),
(\'FK\', \'FKP\', \'FLK\'),
(\'FM\', \'USD\', \'FSM\'),
(\'FO\', \'DKK\', \'FRO\'),
(\'FR\', \'EUR\', \'FRA\'),
(\'GA\', \'XAF\', \'GAB\'),
(\'GB\', \'GBP\', \'GBR\'),
(\'GD\', \'XCD\', \'GRD\'),
(\'GE\', \'GEL\', \'GEO\'),
(\'GF\', \'EUR\', \'GUF\'),
(\'GG\', \'GBP\', \'GGY\'),
(\'GH\', \'GHS\', \'GHA\'),
(\'GI\', \'GIP\', \'GIB\'),
(\'GL\', \'DKK\', \'GRL\'),
(\'GM\', \'GMD\', \'GMB\'),
(\'GN\', \'GNF\', \'GIN\'),
(\'GP\', \'EUR\', \'GLP\'),
(\'GQ\', \'XAF\', \'GNQ\'),
(\'GR\', \'EUR\', \'GRC\'),
(\'GS\', \'GBP\', \'SGS\'),
(\'GT\', \'GTQ\', \'GTM\'),
(\'GU\', \'USD\', \'GUM\'),
(\'GW\', \'XOF\', \'GNB\'),
(\'GY\', \'GYD\', \'GUY\'),
(\'HK\', \'HKD\', \'HKG\'),
(\'HM\', \'AUD\', \'HMD\'),
(\'HN\', \'HNL\', \'HND\'),
(\'HR\', \'HRK\', \'HRV\'),
(\'HT\', \'HTG\', \'HTI\'),
(\'HU\', \'HUF\', \'HUN\'),
(\'ID\', \'IDR\', \'IDN\'),
(\'IE\', \'EUR\', \'IRL\'),
(\'IL\', \'ILS\', \'ISR\'),
(\'IM\', \'GBP\', \'IMN\'),
(\'IN\', \'INR\', \'IND\'),
(\'IO\', \'USD\', \'IOT\'),
(\'IQ\', \'IQD\', \'IRQ\'),
(\'IR\', \'IRR\', \'IRN\'),
(\'IS\', \'ISK\', \'ISL\'),
(\'IT\', \'EUR\', \'ITA\'),
(\'JE\', \'GBP\', \'JEY\'),
(\'JM\', \'JMD\', \'JAM\'),
(\'JO\', \'JOD\', \'JOR\'),
(\'JP\', \'JPY\', \'JPN\'),
(\'KE\', \'KES\', \'KEN\'),
(\'KG\', \'KGS\', \'KGZ\'),
(\'KH\', \'KHR\', \'KHM\'),
(\'KI\', \'AUD\', \'KIR\'),
(\'KM\', \'KMF\', \'COM\'),
(\'KN\', \'XCD\', \'KNA\'),
(\'KP\', \'KPW\', \'PRK\'),
(\'KR\', \'KRW\', \'KOR\'),
(\'KW\', \'KWD\', \'KWT\'),
(\'KY\', \'KYD\', \'CYM\'),
(\'KZ\', \'KZT\', \'KAZ\'),
(\'LA\', \'LAK\', \'LAO\'),
(\'LB\', \'LBP\', \'LBN\'),
(\'LC\', \'XCD\', \'LCA\'),
(\'LI\', \'CHF\', \'LIE\'),
(\'LK\', \'LKR\', \'LKA\'),
(\'LR\', \'LRD\', \'LBR\'),
(\'LS\', \'LSL\', \'LSO\'),
(\'LT\', \'EUR\', \'LTU\'),
(\'LU\', \'EUR\', \'LUX\'),
(\'LV\', \'EUR\', \'LVA\'),
(\'LY\', \'LYD\', \'LBY\'),
(\'MA\', \'MAD\', \'MAR\'),
(\'MC\', \'EUR\', \'MCO\'),
(\'MD\', \'MDL\', \'MDA\'),
(\'ME\', \'EUR\', \'MNE\'),
(\'MF\', \'EUR\', \'MAF\'),
(\'MG\', \'MGA\', \'MDG\'),
(\'MH\', \'USD\', \'MHL\'),
(\'MK\', \'MKD\', \'MKD\'),
(\'ML\', \'XOF\', \'MLI\'),
(\'MM\', \'MMK\', \'MMR\'),
(\'MN\', \'MNT\', \'MNG\'),
(\'MO\', \'MOP\', \'MAC\'),
(\'MP\', \'USD\', \'MNP\'),
(\'MQ\', \'EUR\', \'MTQ\'),
(\'MR\', \'MRO\', \'MRT\'),
(\'MS\', \'XCD\', \'MSR\'),
(\'MT\', \'EUR\', \'MLT\'),
(\'MU\', \'MUR\', \'MUS\'),
(\'MV\', \'MVR\', \'MDV\'),
(\'MW\', \'MWK\', \'MWI\'),
(\'MX\', \'MXN\', \'MEX\'),
(\'MY\', \'MYR\', \'MYS\'),
(\'MZ\', \'MZN\', \'MOZ\'),
(\'NA\', \'NAD\', \'NAM\'),
(\'NC\', \'XPF\', \'NCL\'),
(\'NE\', \'XOF\', \'NER\'),
(\'NF\', \'AUD\', \'NFK\'),
(\'NG\', \'NGN\', \'NGA\'),
(\'NI\', \'NIO\', \'NIC\'),
(\'NL\', \'EUR\', \'NLD\'),
(\'NO\', \'NOK\', \'NOR\'),
(\'NP\', \'NPR\', \'NPL\'),
(\'NR\', \'AUD\', \'NRU\'),
(\'NU\', \'NZD\', \'NIU\'),
(\'NZ\', \'NZD\', \'NZL\'),
(\'OM\', \'OMR\', \'OMN\'),
(\'PA\', \'PAB\', \'PAN\'),
(\'PE\', \'PEN\', \'PER\'),
(\'PF\', \'XPF\', \'PYF\'),
(\'PG\', \'PGK\', \'PNG\'),
(\'PH\', \'PHP\', \'PHL\'),
(\'PK\', \'PKR\', \'PAK\'),
(\'PL\', \'PLN\', \'POL\'),
(\'PM\', \'EUR\', \'SPM\'),
(\'PN\', \'NZD\', \'PCN\'),
(\'PR\', \'USD\', \'PRI\'),
(\'PS\', \'ILS\', \'PSE\'),
(\'PT\', \'EUR\', \'PRT\'),
(\'PW\', \'USD\', \'PLW\'),
(\'PY\', \'PYG\', \'PRY\'),
(\'QA\', \'QAR\', \'QAT\'),
(\'RE\', \'EUR\', \'REU\'),
(\'RO\', \'RON\', \'ROU\'),
(\'RS\', \'RSD\', \'SRB\'),
(\'RU\', \'RUB\', \'RUS\'),
(\'RW\', \'RWF\', \'RWA\'),
(\'SA\', \'SAR\', \'SAU\'),
(\'SB\', \'SBD\', \'SLB\'),
(\'SC\', \'SCR\', \'SYC\'),
(\'SD\', \'SDG\', \'SDN\'),
(\'SE\', \'SEK\', \'SWE\'),
(\'SG\', \'SGD\', \'SGP\'),
(\'SH\', \'SHP\', \'SHN\'),
(\'SI\', \'EUR\', \'SVN\'),
(\'SJ\', \'NOK\', \'SJM\'),
(\'SK\', \'EUR\', \'SVK\'),
(\'SL\', \'SLL\', \'SLE\'),
(\'SM\', \'EUR\', \'SMR\'),
(\'SN\', \'XOF\', \'SEN\'),
(\'SO\', \'SOS\', \'SOM\'),
(\'SR\', \'SRD\', \'SUR\'),
(\'SS\', \'SSP\', \'SSD\'),
(\'ST\', \'STD\', \'STP\'),
(\'SV\', \'USD\', \'SLV\'),
(\'SX\', \'ANG\', \'SXM\'),
(\'SY\', \'SYP\', \'SYR\'),
(\'SZ\', \'SZL\', \'SWZ\'),
(\'TC\', \'USD\', \'TCA\'),
(\'TD\', \'XAF\', \'TCD\'),
(\'TF\', \'EUR\', \'ATF\'),
(\'TG\', \'XOF\', \'TGO\'),
(\'TH\', \'THB\', \'THA\'),
(\'TJ\', \'TJS\', \'TJK\'),
(\'TK\', \'NZD\', \'TKL\'),
(\'TL\', \'USD\', \'TLS\'),
(\'TM\', \'TMT\', \'TKM\'),
(\'TN\', \'TND\', \'TUN\'),
(\'TO\', \'TOP\', \'TON\'),
(\'TR\', \'TRY\', \'TUR\'),
(\'TT\', \'TTD\', \'TTO\'),
(\'TV\', \'AUD\', \'TUV\'),
(\'TW\', \'TWD\', \'TWN\'),
(\'TZ\', \'TZS\', \'TZA\'),
(\'UA\', \'UAH\', \'UKR\'),
(\'UG\', \'UGX\', \'UGA\'),
(\'UM\', \'USD\', \'UMI\'),
(\'US\', \'USD\', \'USA\'),
(\'UY\', \'UYU\', \'URY\'),
(\'UZ\', \'UZS\', \'UZB\'),
(\'VA\', \'EUR\', \'VAT\'),
(\'VC\', \'XCD\', \'VCT\'),
(\'VE\', \'VEF\', \'VEN\'),
(\'VG\', \'USD\', \'VGB\'),
(\'VI\', \'USD\', \'VIR\'),
(\'VN\', \'VND\', \'VNM\'),
(\'VU\', \'VUV\', \'VUT\'),
(\'WF\', \'XPF\', \'WLF\'),
(\'WS\', \'WST\', \'WSM\'),
(\'XK\', \'EUR\', \'XKX\'),
(\'YE\', \'YER\', \'YEM\'),
(\'YT\', \'EUR\', \'MYT\'),
(\'ZA\', \'ZAR\', \'ZAF\'),
(\'ZM\', \'ZMW\', \'ZMB\'),
(\'ZW\', \'ZWL\', \'ZWE\')');
        $this->addSql('CREATE VIEW v_currencies AS SELECT DISTINCT(currency_code) FROM country');
        $this->addSql('ALTER TABLE user ADD COLUMN favorite_currency VARCHAR(4)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
        $this->addSql('DROP TABLE country');
    }
}
